Webkul\UVDesk\CoreBundle\Entity\SavedReplies:
    type: entity
    table: uv_saved_replies
    repositoryClass: Webkul\UVDesk\CoreBundle\Repository\SavedRepliesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        templateId:
            type: integer
            nullable: true
        name:
            type: string
            length: 255
        subject:
            type: string
            length: 255
            nullable: true
        isPredefind:
            type: boolean
            nullable: true
            options:
                default: 1
        templateFor:
            type: string
            nullable: true
            options:
                default: null
        message:
            type: text
        messageInline:
            type: text
            nullable: true
    manyToOne:
        user:
            targetEntity: UserInstance
            inversedBy: userSaveReplies
            joinColumn:
                name: user_id
                referencedColumnName: id
                nullable: true
                onDelete: cascade
    manyToMany:
        groups:
            nullable: true        
            targetEntity: SupportGroup
            joinTable:
                name: uv_saved_replies_groups
                joinColumns:
                    savedReply_id:
                        referencedColumnName: id
                        onDelete: cascade                        
                inverseJoinColumns:
                    group_id:
                        referencedColumnName: id
                        onDelete: cascade           
        teams:
            nullable: true        
            targetEntity: SupportTeam
            joinTable:
                name: uv_saved_replies_teams
                joinColumns:
                    savedReply_id:
                        referencedColumnName: id
                        onDelete: cascade                        
                inverseJoinColumns:
                    subgroup_id:
                        referencedColumnName: id
                        onDelete: cascade