Webkul\UVDesk\CoreBundle\Entity\SupportLabel:
    type: entity
    table: uv_support_label
    repositoryClass: null
    manyToOne:
        user:
            targetEntity: User
            joinColumn:
                name: user_id
                referencedColumnName: id
                onDelete: cascade
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 191
        colorCode:
            type: string
            length: 191
            nullable: true
    lifecycleCallbacks: {  }
