Webkul\UVDesk\CoreBundle\Entity\Tag:
    type: entity
    table: uv_tag
    manyToMany:
        tickets:
            targetEntity: Ticket
            mappedBy: supportTags
    table: null
    repositoryClass: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
