# Ticket List Resources
helpdesk_member_ticket_collection:
    path:     /tickets
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\Ticket::listTicketCollection

helpdesk_member_ticket_collection_xhr:
    path:     /tickets/xhr
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\TicketXHR::listTicketCollectionXHR

helpdesk_member_ticket_collection_mass_action_xhr:
    path:     /tickets/mass-xhr
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\TicketXHR::updateTicketCollectionXHR

helpdesk_member_ticket_collection_load_filter_options_xhr:
    path:     /tickets/filter-options
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\TicketXHR::loadTicketFilterOptionsXHR

helpdesk_member_ticket_collection_search_filter_options_xhr:
    path:     /tickets/search-filter-options
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\TicketXHR::loadTicketCollectionSearchFilterOptionsXHR

# Ticket Resources
helpdesk_member_ticket:
    path:     /ticket/view/{ticketId}
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\Ticket::loadTicket
    defaults: { ticketId: 0 }

helpdesk_member_ticket_xhr:
    path:     /ticket/xhr/{ticketId}
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\TicketXHR::loadTicketXHR
    defaults: { ticketId: 0 }

helpdesk_member_create_ticket:
    path:     /ticket/save
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\Ticket::saveTicket
    methods: [POST, PUT]

search_ticket_filter_options_xhr:
    path: /ticket/search-filter-options
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\TicketXHR::getSearchFilterOptionsXhr

helpdesk_member_trash_ticket:
    path:     /ticket/trash/{ticketId}
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\Ticket::trashTicket

helpdesk_member_delete_ticket:
    path:     /ticket/delete/{ticketId}
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\Ticket::deleteTicket

helpdesk_member_ticket_saved_reply_xhr:
    path:     /ticket/saved-reply-apply/{id}
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\TicketXHR::loadTicketSavedReplies
    defaults: { id: 0 }

helpdesk_member_ticket_add_label_xhr:
    path:     /ticket/labels/save
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\TicketXHR::saveTicketLabel

helpdesk_member_ticket_label_xhr:
    path:     /ticket/labels/update/{ticketLabelId}
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\TicketXHR::ticketLabelXHR
    defaults: { ticketLabelId: 0 }

helpdesk_member_bookmark_ticket_xhr:
    path:     /ticket/bookmark/xhr
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\TicketXHR::bookmarkTicketXHR

helpdesk_member_update_ticket_details_xhr:
    path:     /ticket/update/details/{ticketId}
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\TicketXHR::updateTicketDetails

helpdesk_member_update_ticket_attributes_xhr:
    path:     /ticket/update/attributes/{ticketId}
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\TicketXHR::updateTicketAttributes
    defaults: { ticketId: 0 }

helpdesk_member_ticket_download_attachment:
    path:     /ticket/download/{attachmendId}
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\Ticket::downloadAttachment
    defaults: { attachmendId: 0}

helpdesk_member_ticket_download_attachment_zip:
    path:     /ticket/download-zip/{threadId}
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\Ticket::downloadZipAttachment
    defaults: { threadId: 0}

helpdesk_member_ticket_manage_collaborators_xhr:
    path:     /ticket/collaborator/{id}
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\TicketXHR::updateCollaboratorXHR
    defaults: { id: 0 }

helpdesk_member_ticket_search_filter_options:
    path:     /ticket/search-filter-options
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\TicketXHR::loadTicketSearchFilterOptions

# Ticket Thread Resources
helpdesk_member_thread_collection_xhr:
    path:     /threads/ajax/{ticketId}
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\ThreadXHR::listTicketThreadCollectionXHR
    defaults: { ticketId: 0 }

helpdesk_member_thread_encoded_image_uploader:
    path:     /thread/encoded-images/save/{ticketId}
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\Thread::base64ImageUpload

helpdesk_member_add_ticket_thread:
    path:     /thread/add/{ticketId}
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\Thread::saveThread
    defaults: { ticketId: 0 }

helpdesk_member_thread_xhr:
    path:     /threads/ajax/action/{threadId}
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\Thread::threadXHR
    defaults: { threadId: 0 }

helpdesk_member_thread_update_xhr:
    path:     /threads/update/{threadId}
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\Thread::updateThreadXHR
    defaults: { threadId: 0 }

# Email Templates Resources
email_templates_action:
    path:     /templates
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\Email::templates
    defaults: { panelId: 'settings' }

email_templates_xhraction:
    path:     /template-ajax/{template}
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\Email::templatesxhr
    defaults: { template: 0 }

email_templates_addaction:
    path:     /template/add
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\Email::templateForm
    defaults: { panelId: 'settings' }

email_templates_editaction:
    path:     /template/edit/{template}
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\Email::templateForm
    defaults: { template: 0, panelId: 'settings' }

# Ticket Tag Resources
helpdesk_member_ticket_tag_collection:
    path:     /support-tags
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\Ticket::listTagCollection
    defaults: { panelId: 'productivity' }

helpdesk_member_ticket_tag_collection_xhr:
    path:     /support-tags/xhr
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\TicketXHR::listTagCollectionXHR

helpdesk_member_ticket_create_tag_xhr:
    path:     /support-tags/create/{id}
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\TicketXHR::createTicketTagXHR
    defaults: { id: 0 }

helpdesk_member_update_ticket_tag_xhr:
    path:     /support-tags/update/{tagId}
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\TicketXHR::updateTicketTagXHR
    defaults: { tagId: 0 }

helpdesk_member_remove_ticket_tag_xhr:
    path:     /support-tags/remove/{tagId}
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\TicketXHR::removeTicketTagXHR
    defaults: { tagId: 0 }

# Ticket Type Resources
helpdesk_member_ticket_type_collection:
    path:     /ticket-types
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\Ticket::listTicketTypeCollection
    defaults: { panelId: 'productivity' }

helpdesk_member_ticket_type_collection_xhr:
    path:     /ticket-types/xhr
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\TicketXHR::listTicketTypeCollectionXHR

helpdesk_member_create_ticket_type:
    path:     /ticket-types/create
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\Ticket::ticketType
    defaults: { panelId: 'productivity' }

helpdesk_member_remove_ticket_type:
    path:     /ticket-types/remove/{typeId}
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\TicketXHR::removeTicketTypeXHR
    defaults: { typeId: 0 }

helpdesk_member_update_ticket_type:
    path:     /ticket-types/update/{ticketTypeId}
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\Ticket::ticketType
    defaults: { panelId: 'productivity' }

helpdesk_member_ticket_quick_view_xhr:
    path:     /ticket/quick-view/{ticketId}
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\TicketXHR::getTicketQuickViewDetailsXhr
    defaults: { ticketId: 0 }

# Saved Replies
helpdesk_member_saved_replies:
    path:     /saved-replies
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\SavedReplies::loadSavedReplies
    defaults: { panelId: 'productivity' }

helpdesk_member_saved_replies_xhr:
    path:     /saved-replies/xhr/{template}
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\SavedReplies::savedRepliesXHR
    defaults: {template: 0}

helpdesk_member_update_saved_replies:
    path:     /saved-reply/edit/{template}
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\SavedReplies::updateSavedReplies
    defaults: { panelId: 'productivity', template: 0}

helpdesk_member_create_saved_replies:
    path:     /saved-reply/add/{template}
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\SavedReplies::updateSavedReplies
    defaults: { panelId: 'productivity',  template: 0}

# Apply Prepared Response 
helpdesk_member_ticket_prepared_response_xhr:
    path:     /ticket/prepared-response/xhr/{ticketId}/{id}
    controller: Webkul\UVDesk\CoreFrameworkBundle\Controller\TicketXHR::applyTicketPreparedResponseXHR
    defaults: { ticketId: 0, id: 0 }
